use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

abstract_target 'All' do

  pod 'CocoaAsyncSocket', '~> 7.6.1'

  pod 'Alamofire', '~> 4.4.0'
  pod 'AlamofireObjectMapper', '~> 4.1.0'

  pod 'RealmSwift', '~> 2.7.0'

  pod 'XCGLogger', '~> 5.0.1'
  #pod 'BrightFutures', '~> 1.0.0'

  target 'RMBTClient_iOS' do
    platform :ios, '9.0'

    # Pods for RMBTClient_iOS
    pod 'GCNetworkReachability', '~> 1.3.2'
  end

  target 'RMBTClient_OSX' do
    platform :osx, '10.11'

    # Pods for RMBTClient_OSX
    pod 'GCNetworkReachability', '~> 1.3.2'
  end

  target 'RMBTClient_tvOS' do
    platform :tvos, '9.2'

    # Pods for RMBTClient_tvOS
    # TODO: GCNetworkReachability
  end
end
